services:

  mysql:
    container_name: leximemory-db
    image: mysql:8.0.35
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leximemory
