services:

  mysql:
    container_name: leximemory-db
    image: my_mysql_image_with_data:new_data
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: leximemorydb
